### ISSUE TITLE
Running `docker-compose` build results in error

### ISSUE THREAD

**Issue by owlg** [ummjackson/mastodon-guide#3]
When running 

` docker-compose build`

Ubuntu Xenial encounter this error: 

> An error occurred while installing nio4r (2.0.0), and Bundler cannot continue.
Make sure that `gem install nio4r -v '2.0.0'` succeeds before bundling.
ERROR: Service 'streaming' failed to build: The command '/bin/sh -c BUILD_DEPS="     postgresql-dev     libxml2-dev     libxslt-dev     build-base"  && apk -U upgrade && apk add     $BUILD_DEPS     nodejs     libpq     libxml2     libxslt     ffmpeg     file     imagemagick  && npm install -g npm@3 && npm install -g yarn  && bundle install --deployment --without test development  && yarn  && yarn cache clean  && npm -g cache clean  && apk del $BUILD_DEPS  && rm -rf /tmp/* /var/cache/apk/*' returned a non-zero code: 5
root@ubuntu-512mb-nyc1-01:/home/mastodon/mastodon# gem install nio4r -v '2.0.0'
Building native extensions.  This could take a while...
ERROR:  Error installing nio4r:
        ERROR: Failed to build gem native extension.

Apparently there is an error with trying to install nio4r, please advise

**Comment by ummjackson** [comment]
Quick search on the Mastodon repo gave this: https://github.com/tootsuite/mastodon/issues/1205

Looks like it *is* a memory issue... I had a 1GB instance building fine so it looks like that might be the ultimate minimum requirement. I really recommend 2GB though, otherwise you'll have headaches in the future.
